### ISSUE TITLE
This solution and bibtex problem

### ISSUE THREAD

**Issue by kachkaev** [marcuswhybrow/texshop-pdflatex#1]
Marcus, do you know any way to overcome a bibtex issue that happens when you start using this solution?

After all aux files are moved into 'build' or whatever other subfolder, bibtex can no longer create the bibliography index and it seems that there's no way to fix that. Please let know if you could manage this! Without being able to work with citations, the idea of moving aux and other files away loses its awesomeness...

Cheers!

**Comment by marcuswhybrow** [comment]
Hi kachkaev, I have forgotten the details of TexShop since it has been a year, but instead of this texshop-pdflate script my "Tex (default: pdftex)" box (Preferences>Engine) as described in the readme reads:

`pdftex --file-line-error --shell-escape --synctex=1 --output-directory=build`

I think it's I arrived at this approach after running into similar problems with this script, however I have also read that bibtex is not compatible with the `--output-directory` flag at all.

That's all I remember/found out again,
Good look with your document!

**Comment by kachkaev** [comment]
Yeah, looks like you're right about bibtex. I could not find any workaround as well. So I'm afraid that your method is only good for projects with no citations and the only solution otherwise will be keeping all those aux, log and other files in the same directory and write a script that will delete them on demand before you finish working, commit the changes to git/svn or simply share your files. That's a shame that bibtex still does not support anything like `--input-directory` parameter...

**Comment by jakewilliami** [comment]
@kachkaev See [my fork](https://github.com/jakewilliami/texshop-pdflatexmk).
